#ifndef __ZMQ_PLATFORM_HPP_INCLUDED__
#define __ZMQ_PLATFORM_HPP_INCLUDED__

#define ZMQ_USE_CV_IMPL_PTHREADS 1
#define ZMQ_IOTHREAD_POLLER_USE_EPOLL 1
#define ZMQ_IOTHREAD_POLLER_USE_EPOLL_CLOEXEC 1
#define ZMQ_POLL_BASED_ON_POLL 1

#define HAVE_POSIX_MEMALIGN 1
#define ZMQ_CACHELINE_SIZE 64
#define HAVE_FORK 1
#define HAVE_CLOCK_GETTIME 1
#define ZMQ_HAVE_UIO 1
#define ZMQ_HAVE_NOEXCEPT 1
#define ZMQ_HAVE_EVENTFD 1
#define ZMQ_HAVE_EVENTFD_CLOEXEC 1
#define ZMQ_HAVE_IFADDRS 1
#define ZMQ_HAVE_SO_BINDTODEVICE 1
#define ZMQ_HAVE_SOCK_CLOEXEC 1
#define ZMQ_HAVE_SO_KEEPALIVE 1
#define ZMQ_HAVE_SO_PEERCRED 1
#define ZMQ_HAVE_TCP_KEEPCNT 1
#define ZMQ_HAVE_TCP_KEEPIDLE 1
#define ZMQ_HAVE_TCP_KEEPINTVL 1
#define ZMQ_HAVE_PTHREAD_SETNAME_2 1
#define ZMQ_HAVE_PTHREAD_SET_AFFINITY 1
#define HAVE_ACCEPT4 1
#define HAVE_STRNLEN 1
#define ZMQ_HAVE_STRLCPY 1
#define ZMQ_HAVE_IPC 1
#define ZMQ_HAVE_STRUCT_SOCKADDR_UN 1
#define ZMQ_USE_BUILTIN_SHA1 1

#endif
